- .gitignore
- app/models/cart_item.rb
- app/models/genre.rb
- config/initializers/new_framework_defaults.rb
- db/migrate/20210516220142_create_genres.rb
- db/migrate/20210516220643_create_cart_items.rb
- db/schema.rb
- test/fixtures/cart_items.yml
- test/fixtures/genres.yml
- test/models/cart_item_test.rb
- test/models/genre_test.rb
> [Create model ] cart_item genre

- app/models/admin.rb
- app/models/customer.rb
- app/models/product.rb
- config/initializers/devise.rb
- config/initializers/new_framework_defaults.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20210516105138_create_products.rb
- db/migrate/20210516120728_devise_create_admins.rb
- db/migrate/20210516123415_devise_create_customers.rb
- db/schema.rb
- test/fixtures/admins.yml
- test/fixtures/customers.yml
- test/fixtures/products.yml
- test/models/admin_test.rb
- test/models/customer_test.rb
- test/models/product_test.rb
customer、admin、productモデル追加しました。
> モデル追加customer,admin,product

- config/routes.rb
> add-routing

- app/assets/javascripts/admin/genres.coffee
- app/assets/javascripts/admin/oder_items.coffee
- app/assets/javascripts/admin/oders.coffee
- app/assets/stylesheets/admin/genres.scss
- app/assets/stylesheets/admin/oder_items.scss
- app/assets/stylesheets/admin/oders.scss
- app/controllers/admin/genres_controller.rb
- app/controllers/admin/oder_items_controller.rb
- app/controllers/admin/oders_controller.rb
- app/helpers/admin/genres_helper.rb
- app/helpers/admin/oder_items_helper.rb
- app/helpers/admin/oders_helper.rb
- test/controllers/admin/genres_controller_test.rb
- test/controllers/admin/oder_items_controller_test.rb
- test/controllers/admin/oders_controller_test.rb
#コントローラ追加
##管理者側
admin/oders
admin/oder_items
admin/genres
> [Add]controller,admin/oders,admin/oder_items,admin/genres

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/admin/oders_controller.rb
- app/views/admin/oders/index.html.erb
- app/views/admin/oders/show.html.erb
- db/schema.rb
・view追加しました
ordes(index/show),genre(index,edit)
・app/assets/javascripts/application.js　記述追加
・css→scssに変更
> [Add]viewファイルgenre/order

- app/assets/stylesheets/application.scss
- app/controllers/admin/genres_controller.rb
- app/controllers/admin/orders_controller.rb
- app/models/genre.rb
- app/models/order.rb
- app/models/order_item.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/orders/index.html.erb
- app/views/admin/orders/show.html.erb
- config/routes.rb
admin側
order (index・showページ),genre(index・editページ) 作成しました。
確認お願いします！
app/assets/stylesheets/application.scss　@import "bootstrap";追加
app/controllers/admin/genres_controller.rb
app/controllers/admin/orders_controller.rb
app/models/genre.rb　アソシエーション追加
app/models/order.rb　アソシエーション追加
app/models/order_item.rb　アソシエーション追加
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
config/routes.rb　→orderスペルミスあったので訂正
> [Add]admin/order/jenreページ

- app/controllers/public/deliveries_controller.rb
- app/controllers/public/products_controller.rb
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/views/public/deliveries/index.html.erb
- app/views/public/products/index.html.erb
- app/views/public/products/show.html.erb
- config/initializers/kaminari_config.rb
> 20210519途中

- app/assets/stylesheets/application.scss
- app/controllers/admin/products_controller.rb
- app/views/admin/products/edit.html.erb
- app/views/admin/products/new.html.erb
- app/views/admin/products/show.html.erb
- app/views/public/orders/complete.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
>  for now 5/20

- app/controllers/admin/customers_controller.rb
- app/controllers/public/customers_controller.rb
- app/models/customer.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/public/customers/edit.html.erb
- app/views/public/registrations/new.html.erb
- config/routes.rb
以下の点について、変更・追記しました。確認お願いします。
[controller]
　　modified:   app/controllers/admin/customers_controller.rb
modified:   app/controllers/public/customers_controller.rb
[model] → アソシエーション追記
modified:   app/models/customer.rb
[View]
modified:   app/views/admin/customers/edit.html.erb
modified:   app/views/admin/customers/index.html.erb
modified:   app/views/admin/customers/show.html.erb
modified:   app/views/public/customers/edit.html.erb
modified:   app/views/public/registrations/new.html.erb
[routing] → 管理者ログインした後の遷移ページ
modified:   config/routes.rb
> Imaken [Add View file etc..]

- app/views/public/homes/top.html.erb
> [Update]home/top

- app/assets/stylesheets/products.scss
- app/controllers/public/cart_items_controller.rb
- app/controllers/public/products_controller.rb
- app/helpers/cart_items_helper.rb
- app/helpers/products_helper.rb
- app/models/cart_item.rb
- app/models/genre.rb
- app/models/product.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/products/index.html.erb
- app/views/public/products/show.html.erb
- config/initializers/assets.rb
- config/routes.rb
cart_itemのindexのページの機能を作成しました。
期日を過ぎまして申し訳ありません。
また、コードを整える前ですが、このページがないと確認できないところがあると思いますので取り急ぎpushしました。
ルーティングの記載が間違えていましたので、変更しました。
> cart_item_index-function

- app/controllers/public/orders_controller.rb
- app/models/genre.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/orders/show.html.erb
以下を修正加筆しました。
・基本機能の実装
ーviews order/show
・画像表示の参照モデルの訂正
ーorder/confirm,
・金額を３桁区切りにするメソッドの追加
ー".to_s(:delimited)"
> add order/show, fix order/confirm, add ".to_s(:delimited)"

- app/controllers/public/orders_controller.rb
- app/models/order.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/orders/show.html.erb
何度もプルリクしてすみません。
pubric側orderの機能はこれで完了できたと思います。
> fix all  function of pubric/order

- app/controllers/admin/order_items_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/admin/products_controller.rb
- app/views/admin/orders/show.html.erb
- app/views/admin/products/edit.html.erb
- app/views/admin/products/index.html.erb
- app/views/admin/products/new.html.erb
- app/views/public/orders/new.html.erb
- config/application.rb
遅くなってすいません。
確認お願いします！
admin側
・注文一覧・詳細ページ修正
・商品新規登録・編集画面、バリデーション追記
modified:   app/controllers/admin/order_items_controller.rb
modified:   app/controllers/admin/orders_controller.rb
modified:   app/controllers/admin/products_controller.rb
modified:   app/views/admin/orders/show.html.erb
modified:   app/views/admin/products/edit.html.erb
modified:   app/views/admin/products/index.html.erb
modified:   app/views/admin/products/new.html.erb
modified:   app/views/public/orders/new.html.erb
modified:   config/application.rb　←日本時刻に変更
> [Update]admin/order

- app/assets/stylesheets/orders.scss
- app/controllers/public/orders_controller.rb
- app/models/delivery.rb
- app/views/public/orders/complete.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/orders/show.html.erb
- config/routes.rb
> add redirect ,fix layout 

- app/controllers/admin/products_controller.rb
- app/controllers/public/orders_controller.rb
- app/views/public/orders/index.html.erb
下記修正しました！
・配送先氏名
・商品新規投稿後の遷移先(商品詳細ページへ)
> [Update]配送先情報・商品登録

- app/assets/stylesheets/orders.scss
- app/assets/stylesheets/products.scss
- app/controllers/public/products_controller.rb
- app/models/genre.rb
- app/models/product.rb
- app/views/layouts/_genresearch.html.erb
- app/views/layouts/_search.html.erb
- app/views/public/homes/top.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/products/index.html.erb
- app/views/public/products/show.html.erb
- config/routes.rb
ジャンル検索機能を追加しました。
”確認画面へ進む”、”注文を確定する”ボタンのレイアウトを修正しました。
> Add genre search, fix btn layout 

- app/views/public/products/index.html.erb
> Fix product index

- README.md
> README-fix

- app/views/admin/orders/show.html.erb
showページのボーダー追加しました
app/views/admin/orders/show.html.erb
> [Update]admin/order/show

- app/views/admin/products/show.html.erb
- app/views/layouts/application.html.erb
・管理者側ページでヘッダーロゴを押すと注文一覧（管理者トップページ）に遷移
・admin/product/showのfill を削除(Windowsでは画像が表示されなかったので)
> Add admin logo to product index,etc

- app/assets/stylesheets/application.scss
- app/controllers/public/homes_controller.rb
- app/views/admin/orders/show.html.erb
- app/views/layouts/about.html.erb
- app/views/public/homes/top.html.erb
aboutページ修正しました。
　　modified:   app/assets/stylesheets/application.scss
modified:   app/controllers/public/homes_controller.rb
modified:   app/views/admin/orders/show.html.erb
modified:   app/views/public/homes/top.html.erb
　　app/views/layouts/about.html.erb　追加！
> [Update]aboutページlayout
